<?php

namespace AppBundle\Repository;

/**
 * RegistroInvitadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistroInvitadoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventsByFilters($event, $email, $starDate, $endDate){
        $q = $this->createQueryBuilder('i')
            ->where('i.delete = 0')
        ;

        if($event != null){
            $q->andWhere($q->expr()->like('i.nombreEvento',$q->expr()->literal('%'. $event . '%')));
        }

        if($email != null){
            $q->andWhere($q->expr()->like('i.email', $q->expr()->literal('%'. $email . '%')));
        }

        if($starDate != null && $endDate != null){
            $q
                ->andWhere($q->expr()->between('i.fecha',':startDate', ':endDate'))
                ->setParameter('startDate',$starDate->format('Y-m-d'))
                ->setParameter('endDate', $endDate->format('Y-m-d'))
            ;
        }

        return $q->getQuery()->getResult();
    }
}
