<?php

namespace AppBundle\Repository;

/**
 * UserDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDetailRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByName($name){
        $q = $this->createQueryBuilder('u')
            ->innerJoin('u.userId','us')
        ;
        $q->andWhere($q->expr()->like('u.nombre', $q->expr()->literal('%' . $name . '%')));

        return $q->getQuery()->getResult();
    }
}
