app:
    resource: '@AppBundle/Controller/'
    type: annotation

#### fos oauth server ####
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# Login FrontEnd ##
front_login:
    path: /index/login
    defaults: { _controller: AppBundle:Security:loginFront }

front_logout:
    path: /index/logout

front_login_check:
    path: /index/login_check

front_initial_page:
   path: /index/inicial/
   defaults: { _controller: AppBundle:Security:initialPage }

## Login BackEnd ###
back_login:
    path: /admin/login
    defaults: { _controller: AppBundle:Security:login }

back_login_check:
    path: /admin/login_check

back_logout:
    path: /admin/logout